version: "3.9"

services:
  frontend:
    build: ./my-react-app
    container_name: frontend_c
    ports:
      - "3000:3000"
    volumes:
      - ./my-react-app:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend
    restart: always
    command: npm start

  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: recipehub
      DB_PORT: 3306
      NODE_ENV: development
    depends_on:
      mysql_db:
        condition: service_healthy  # Wait for MySQL to be healthy
    restart: always
    command: npm run dev

  mysql_db:
    image: mysql:8.0
    container_name: recipehub_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: recipehub
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: recipehub_phpmyadmin
    restart: always
    depends_on:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123
    ports:
      - "8081:80"

volumes:
  mysql_data: